<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
class ForecastingDataSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('peak_seasons')->insert([
        ['item' => 'ampalaya','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'ampalaya','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'ampalaya','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'ampalaya','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'ampalaya','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'ampalaya','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'atis','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'atis','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'atis','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'atis','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'avocado','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'avocado','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'avocado','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'avocado','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'balimbing','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'balimbing','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'balimbing','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'balimbing','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'bamboo shots','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'bamboo shots','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'bamboo shots','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'bamboo shots','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'bamboo shots','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'bamboo shots','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'bamboo shots','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'bamboo shots','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana flower','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana flower','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana flower','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana flower','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana flower','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'banana flower','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'batani','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'batani','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'batani','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'batani','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'batani','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cabbage','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cabbage','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cabbage','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'caimito','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'caimito','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'caimito','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'caimito','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'caimito','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'caimito','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'caimito','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'calamansi','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'calamansi','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'calamansi','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cassava leaves','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chayote','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chayote','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chayote','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chayote','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chayote','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chayote','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chicharo','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chicharo','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chicharo','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chicharo','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chico','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'chico','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'coconut','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'coconut','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'coconut','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'coconut','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'corn','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'corn','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'corn','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'corn','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cucumber','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cucumber','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'cucumber','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'dalandan','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'dalandan','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'dalandan','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'dalandan','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'dalandan','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'duhat','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'duhat','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'duhat','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'duhat','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'duhat','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'duirian','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'duirian','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'duirian','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'durian','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'durian','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'durian','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'durian','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'gabi','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'gabi','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'gabi','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'gabi','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'gabi','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'garlic','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'garlic','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'garlic','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'garlic','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'garlic','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'garlic','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'guyabano','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'guyabano','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'guyabano','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'guyabano','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kaimito','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kaimito','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kaimito','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kalabasa','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kalabasa','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kalabasa','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kamatsile','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kamatsile','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kamatsile','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kamatsile','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kamias','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kamias','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kamias','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kangkong','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kasuy','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kasuy','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'katuray','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'katuray','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'katuray','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'katuray','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'katuray','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'katuray','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kiat-kiat','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kiat-kiat','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kiat-kiat','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kiat-kiat','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kinchay','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kinchay','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'kinchay','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'langka','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'langka','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'langka','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lansones','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lansones','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lansones','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lansones','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lansones','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lanzones','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lanzones','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lanzones','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lanzones','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lanzones','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lettuce','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lettuce','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'lettuce','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'longan','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'longan','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'longan','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'longan','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'longan','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'luya','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mabolo','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mabolo','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mabolo','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'makopa','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'makopa','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'makopa','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'malunggay','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mango','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mango','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mango','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mango','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'Mangosteen','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'Mangosteen','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'Mangosteen','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'Mangosteen','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'Mangosteen','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'Mangosteen','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'melon','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'melon','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'melon','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'melon','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'mushrooms','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'okra','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'okra','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'okra','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'okra','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'okra','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'okra','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'okra','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pakwan','month'=>'','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pakwan','month'=>'','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pakwan','month'=>'','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pakwan','month'=>'','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pakwan','month'=>'','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'papaya','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'patatas','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'patatas','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'patola','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'patola','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'patola','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'patola','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'patola','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'patola','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peanuts','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peas','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peas','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peas','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peas','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peas','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'peas','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pepper green','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pepper green','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pepper green','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pepper green','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pepper green','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pepper green','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'petchay','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'petchay','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'petchay','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'petchay','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'petchay','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'petchay','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'petchay','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'petchay','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'petchay','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pinya','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pinya','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pinya','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pomelo','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pomelo','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'pomelo','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rambutan','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rambutan','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rambutan','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'remolatsa','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'remolatsa','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'remolatsa','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'remolatsa','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'remolatsa','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rice','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rice','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rice','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rice','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rice','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rice','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rice','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rice','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'rice','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'saluyot','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'saluyot','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'saluyot','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'saluyot','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sampaloc','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sampaloc','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sampaloc','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'santol','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'santol','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'santol','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sigarilyas','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sigarilyas','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sigarilyas','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sili','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sili','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sili','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sili','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sili','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sili','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sili','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sili','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'singkamas','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'singkamas','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'Siniguelas','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'Siniguelas','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'Siniguelas','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sitaw','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sitaw','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sitaw','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sitaw','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sitaw','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'sitaw','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'squash','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'squash','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'squash','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'squash','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'squash','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'squash','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'suha','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'talong','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'talong','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'talong','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'taro leaves','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'taro leaves','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'taro leaves','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'taro leaves','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'taro leaves','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'tiesa','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'tiesa','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'tomatoes','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'tomatoes','month'=>'july','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'tomatoes','month'=>'august','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'ubas','month'=>'september','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'ubas','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'ubas','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'ubas','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'upo','month'=>'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'upo','month'=>'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'upo','month'=>'october','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'upo','month'=>'november','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'upo','month'=>'december','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'upo','month'=>'january','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'winter melon','month'=>	'february','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'winter melon','month'=>	'march','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'winter melon','month'=>	'april','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'winter melon','month'=>	'may','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
        ['item' => 'winter melon','month' => 'june','created_at'=>Carbon::now(),'updated_at'=>Carbon::now()]
      ]);
    }
}
