<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
class SubCategoryTable extends Seeder
{
  /**
  * Run the database seeds.
  *
  * @return void
  */
  public function run()
  {
    //  DB::table('sub_categories')->truncate();


    DB::table('sub_categories')->insert([
      ['category_id'=>1,'subcategory_name'=>"acorn squash",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"alfalfa sprout",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"amaranth",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"anise",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"artichoke",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"arugula",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"asparagus",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"aubergine",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"azuki bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"banana squash",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"basil",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"bean sprout",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"beet",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"black bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"black-eyed pea",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"bok choy",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"borlotti bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"broad beans",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"broccoflower",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"broccoli",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"brussels sprout",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"butternut squash",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"cabbage",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"calabrese",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"caraway",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"carrot",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"cauliflower",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"cayenne pepper",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"celeriac",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"celery",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"chamomile",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"chard",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"chayote",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"chickpea",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"chives",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"cilantro",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"collard green",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"corn",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"corn salad",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"courgette",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"cucumber",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"daikon",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"delicata",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"dill",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"eggplant",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"endive",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"fennel",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"fiddlehead",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"frisee",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"garlic",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"gem squash",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"ginger",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"green bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"green pepper",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"habanero",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"herbs and spice",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"horseradish",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"hubbard squash",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"jalapeno",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"jerusalem artichoke",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"jicama",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"kale",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"kidney bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"kohlrabi",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"lavender",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"leek ",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"legume",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"lemon grass",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"lentils",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"lettuce",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"lima bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"mamey",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"mangetout",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"marjoram",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"mung bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"mushroom",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"mustard green",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"navy bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"new zealand spinach",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"nopale",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"okra",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"onion",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"oregano",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"paprika",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"parsley",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"parsnip",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"patty pan",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"pea",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"pinto bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"potato",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"pumpkin",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"radicchio",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"radish",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"rhubarb",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"rosemary",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"runner bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"rutabaga",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"sage",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"scallion",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"shallot",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"skirret",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"snap pea",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"soy bean",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"spaghetti squash",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"spinach",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"squash ",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"sweet potato",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"tabasco pepper",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"taro",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"tat soi",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"thyme",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"topinambur",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"tubers",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"turnip",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"wasabi",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"water chestnut",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"watercress",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"white radish",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"yam",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>1,'subcategory_name'=>"zucchini",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()]

    ]);

    DB::table('sub_categories')->insert([
      ['category_id'=>2,'subcategory_name'=>"apple",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"apricot",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"avocado",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"banana",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"bell pepper",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"bilberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"blackberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"blackcurrant",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"blood orange",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"blueberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"boysenberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"breadfruit",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"canary melon",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"cantaloupe",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"cherimoya",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"cherry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"chili pepper",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"clementine",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"cloudberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"coconut",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"cranberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"cucumber",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"currant",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"damson",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"date",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"dragonfruit",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"durian",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"eggplant",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"elderberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"feijoa",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"fig",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"goji berry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"gooseberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"grape",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"grapefruit",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"guava",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"honeydew",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"huckleberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"jackfruit",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"jambul",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"jujube",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"kiwi fruit",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"kumquat",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"lemon",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"lime",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"loquat",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"lychee",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"mandarine",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"mango",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"mulberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"nectarine",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"nut",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"olive",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"orange",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"pamelo",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"papaya",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"passionfruit",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"peach",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"pear",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"persimmon",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"physalis",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"pineapple",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"plum",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"pomegranate",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"pomelo",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"purple mangosteen",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"quince",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"raisin",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"rambutan",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"raspberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"redcurrant",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"rock melon",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"salal berry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"satsuma",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"star fruit",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"strawberry",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"tamarillo",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"tangerine",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"tomato",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"ugli fruit",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>2,'subcategory_name'=>"watermelon",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],

    ]);

    DB::table('sub_categories')->insert([
      ['category_id'=>3,'subcategory_name'=>"Alumahan",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Bisugo",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Salay-Salay",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Galunggong",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Salmon",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Bangus",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Dalagang Bukid",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Dilis",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Yellow-Fin",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Kitang ",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Maya-Maya",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Sapsap",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Tulingan",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Hiwas",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Lapu-Lapu",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Salmonete",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Tilapia",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],
      ['category_id'=>3,'subcategory_name'=>"Tawilis",'created_at'=>Carbon::now(),'updated_at'=>Carbon::now()],

    ]);
  }
}
